# Generated by Django 4.2.1 on 2023-05-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AddField(
            model_name='company',
            name='about',
            field=models.TextField(default='Your default value here'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='company',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('IT', 'IT'), ('NON IT', 'NON IT')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
